
# The standard flow calls msbuild.exe. We need to
# overwrite this default behavior here.
build_script:
  - cmd: call appveyor.bat

# We don't need tests right now.
test: off

artifacts:
  # Push the entire "build" folder as a zip
  - path: build

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    # push contents of deploy folder
    artifact: deploy\*
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true      # deploy on tag push only
