
# We don't need tests right now.
test: off

# The standard flow calls msbuild.exe. We need to
# overwrite this default behavior here.
build_script:
  - cmd: call appveyor.bat

artifacts:
  - path: build  # Push the entire "build" folder as a zip
  - path: deploy\monotide-*.zip

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    auth_token:
      secure: GlPci9QnLJxVkwdcLb6l1v0Std1gZw7kj+9Oyg/emy5H8Npnf8w6B9yXMH/DhNq2
    draft: false
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true      # deploy on tag push only
